
" ---------------------------------------------------------------------------
" Options
" ---------------------------------------------------------------------------

" We don't want vi-compatible behaviour. Should be set at the very top.
set nocompatible

" Allow switching to other buffers even if current is unsaved
set hidden

" Line settings
set number
set numberwidth=4
set textwidth=90
set nowrap
set colorcolumn=91
highlight ColorColumn ctermbg=233

" Indentation settings
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set shiftround
set breakindent

" More indentation for python
autocmd FileType python setlocal shiftwidth=4 tabstop=4 softtabstop=4

" Always show status line
set laststatus=2

" Press F2 for 'paste mode', for properly pasting external stuff into vim
set pastetoggle=<F2>

" Easier handling of the * register
set clipboard=unnamed

" Smarter backspace key
set backspace=indent,eol,start

" Disable mouse
set mouse=

" Search options
set hlsearch
set incsearch
set ignorecase
set smartcase

" Folding
set foldmethod=indent
set foldlevelstart=99   " folds open by default

" Remove <esc> delay
set timeoutlen=1000
set ttimeoutlen=0

set history=1000

" Persistent undo - available since vim 7.3
if has('persistent_undo') && exists("&undodir")
  set undodir=$HOME/.config/nvim/undo
  set undofile
  set undolevels=700
  set undoreload=5000
endif

" Disable backups and swap files - they trigger too many events for file system
" watchers
set nobackup
set nowritebackup
set noswapfile


" ---------------------------------------------------------------------------
" Mappings
" ---------------------------------------------------------------------------

let mapleader = ' '

inoremap jk <esc>

" Save easily
" Might require disabling terminal suspend by adding 'stty -ixon' to shell
" startup script
nnoremap <c-s> :update<cr>
inoremap <c-s> <c-o>:update<cr>
vnoremap <c-s> <c-c>:update<cr>

" Quit easily
noremap <leader>q :quit<cr>
noremap <leader>Q :qa!<cr>

" Easier saving. Might require disabling terminal suspend by adding 'stty " -ixon'
" to shell startup script
nnoremap <c-s> :update<CR>
inoremap <c-s> <c-o>:update<CR>
vnoremap <c-s> <c-c>:update<CR>

" Easy editing and loading of vimrc
nnoremap <leader>V :vsplit $MYVIMRC<cr>
nnoremap <leader>S :source $MYVIMRC<cr>

" Shortcuts to open files in the same directory as current file
noremap <leader>oe :e <c-r>=expand("%:p:h") . "/" <cr>
noremap <leader>ot :tabe <c-r>=expand("%:p:h") . "/" <cr>
noremap <leader>os :split <c-r>=expand("%:p:h") . "/" <cr>
noremap <leader>ov :vsplit <c-r>=expand("%:p:h") . "/" <cr>

" Emacsy bindings for BOL/EOL
inoremap <c-e> <end>
inoremap <c-a> <esc>I
nnoremap <c-a> ^

" Clear highlighting
noremap <c-n> :nohl<cr>
vnoremap <c-n> :nohl<cr>
inoremap <c-n> :nohl<cr>

" Easier moving of code blocks in visual mode
vnoremap < <gv
vnoremap > >gv

" Ctrl-up/down to search command history based on characters typed so far
cnoremap <c-k> <up>
cnoremap <c-j> <down>

" Easier copy-to-clipboard
nnoremap Y "+y
vnoremap Y "+y

" Select previously pasted text
noremap <expr> gp '`[' . strpart(getregtype(), 0, 1) . '`]'

" Easier reindenting in visual mode
vnoremap < <gv
vnoremap > >gv

" Easier moving between tabs.
" Tricky to map Alt in terminal vim. The below mapping works in gnome terminal.
" Generated by hitting Ctrl-v, then Alt-m/n in insert mode. Doesn't work if you
" manually type out ^[m.
" See http://stackoverflow.com/questions/6778961/alt-key-shortcuts-not-working-on-gnome-terminal-with-vim
noremap e <esc>:tabprevious<CR>
noremap r <esc>:tabnext<CR>
noremap E <esc>:tabfirst<CR>
noremap R <esc>:tablast<CR>

" Easier scrolling through command history
cnoremap <c-k> <Up>
cnoremap <c-j> <Down>


" ---------------------------------------------------------------------------
" Abbreviations
" ---------------------------------------------------------------------------

" Convenient separator
iabbrev --- -------------------------------------------------------------------------------


" ---------------------------------------------------------------------------
"  Functions & Misc
" ---------------------------------------------------------------------------

" Enable loading plugins for specific file-types
filetype plugin indent on

" Enable syntax highlighting
syntax on


" Jump to the last edit position when opening files
augroup LastPosition
	autocmd! BufReadPost *
		\ if line("'\"") > 0 && line("'\"") <= line("$") |
		\     exe "normal! g`\"" |
		\ endif
augroup END

" Strip trailing whitespace
function! StripTrailingWhitespace()
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfunction

augroup StripTrailingWhitespace
  autocmd! *
    \ autocmd BufWritePre <buffer> :call
    \ StripTrailingWhitespace()
augroup END

augroup ShowWhitespace

augroup END


" ---------------------------------------------------------------------------
" Plugins
" ---------------------------------------------------------------------------

call plug#begin()

" Plug 'frankier/neovim-colors-solarized-truecolor-only'  " true-color fork of solarized
" Plug 'trevordmiller/nova-vim'
Plug 'mhartington/oceanic-next'

Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-surround'
Plug 'jiangmiao/auto-pairs'

call plug#end()


" -------------------------------------
" Color scheme
" -------------------------------------

" Enable true colors
set termguicolors

set background=dark
colorscheme OceanicNext
