[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = [
  "E", "F", "N", "D", "S", "FBT", "B", "C4", "T20", "PT", "RET", "SIM", "RUF",
]
ignore = [
  "D1",
  "D201",

  # When the above rule categories are enabled, we must ignore the following rules to
  # prevent conflicts with ruff's formatter. 
  # See: https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
  "W191",
  "E111",
  "E114",
  "E117",
  "D206",
  "D300",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "COM812",
  "COM819",
  "ISC001",
  "ISC002",
]
unfixable = [
  "T20",  # don't auto-remove print-statements
  "F841", # don't auto-remove (seemingly) unused variables
  "F401", # don't auto-remove (seemingly) unused imports
]
