# This file handles setting of various environment variables EXCEPT modifications to
# $PATH. $PATH modifications are stored in $DOTFILES_PATH/zsh/config/path.zsh. See related
# notes in that file.
# Also see $DOTFILES_PATH/zsh/config/plugins.zsh for plugin specific env vars.


# The all-important path to our dotfiles. This is assumed in all other config.
export DOTFILES_PATH=$HOME/.dotfiles


# -------------------------------------------------------------------------------
# General
# -------------------------------------------------------------------------------

# Default editors
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'


# -------------------------------------------------------------------------------
# nvim
# -------------------------------------------------------------------------------

export NVIM_VENVS_PATH=$HOME/.config/nvim/venvs
export NVIM_PY3_VENV_PATH=$HOME/.config/nvim/venvs/neovim_py_3


# -------------------------------------------------------------------------------
# pew
# -------------------------------------------------------------------------------
export WORKON_HOME=$HOME/.virtualenvs
