
# Disable terminal suspension (usually ctrl-s)
stty -ixon


ZSH_CONFIG_PATH=$DOTFILES_PATH/zsh/config


# Source $PATH modifications. See notes in this file.
source $ZSH_CONFIG_PATH/path.zsh


source $ZSH_CONFIG_PATH/options.zsh


source $ZSH_CONFIG_PATH/mappings.zsh


# Source plugin system and plugins. Should do this after sourcing mappings, since
# some plugins require things like vi-mode to be set, to function properly.
source $ZSH_CONFIG_PATH/plugins.zsh
