
# Disable terminal suspension (usually ctrl-s)
stty -ixon


ZSH_CONFIG_PATH=$DOTFILES_PATH/zsh/config


# Source $PATH modifications. See notes in this file.
source $ZSH_CONFIG_PATH/path.zsh


source $ZSH_CONFIG_PATH/options.zsh


source $ZSH_CONFIG_PATH/mappings.zsh


# Source plugin system and plugins. Should do this after sourcing mappings, since
# some plugins require things like vi-mode to be set, to function properly.
source $ZSH_CONFIG_PATH/plugins.zsh


source $ZSH_CONFIG_PATH/aliases.zsh


# Hook up asdf runtime for various languages. This should be after any other config that
# tweaks paths to find language binaries.
source $DOTFILES_PATH/asdf/external/asdf/asdf.sh
# source $DOTFILES_PATH/asdf/external/asdf/completions/_asdf
